// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIyJ7JjoZW7s1QUQOcAf147uQ5Bko3y50',
    appId: '1:669606401529:web:d54fbe6d083c90b8cd5928',
    messagingSenderId: '669606401529',
    projectId: 'test-60754',
    authDomain: 'test-60754.firebaseapp.com',
    storageBucket: 'test-60754.appspot.com',
    measurementId: 'G-DMPGYEGMEZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr4xOoVzJdh1TUWNWi6hGNzqsIsqUK5LA',
    appId: '1:669606401529:android:2ef7c7829f3e2b76cd5928',
    messagingSenderId: '669606401529',
    projectId: 'test-60754',
    storageBucket: 'test-60754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGO-eaVfvjt6k3KHu8B_itXp2OvEAYKcE',
    appId: '1:669606401529:ios:485572f761b880a6cd5928',
    messagingSenderId: '669606401529',
    projectId: 'test-60754',
    storageBucket: 'test-60754.appspot.com',
    iosBundleId: 'com.example.clase11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGO-eaVfvjt6k3KHu8B_itXp2OvEAYKcE',
    appId: '1:669606401529:ios:d38ecfd64ea9291acd5928',
    messagingSenderId: '669606401529',
    projectId: 'test-60754',
    storageBucket: 'test-60754.appspot.com',
    iosBundleId: 'com.example.clase11.RunnerTests',
  );
}
