// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6d7sivpQ7If6wy8HW8Qs9qcc3SrsGwcU',
    appId: '1:824869796384:web:e16ba7c45aa32c94fa5a45',
    messagingSenderId: '824869796384',
    projectId: 'upload-image-9f053',
    authDomain: 'upload-image-9f053.firebaseapp.com',
    storageBucket: 'upload-image-9f053.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ducFHyuqwLmlDxoztGNXhUSKHIV377w',
    appId: '1:824869796384:android:ff40d6d62d4483a4fa5a45',
    messagingSenderId: '824869796384',
    projectId: 'upload-image-9f053',
    storageBucket: 'upload-image-9f053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3YuUD4rPfwHQnH1fuBmGXqmoe9hT80t4',
    appId: '1:824869796384:ios:e596875b03eecd31fa5a45',
    messagingSenderId: '824869796384',
    projectId: 'upload-image-9f053',
    storageBucket: 'upload-image-9f053.appspot.com',
    iosBundleId: 'com.example.uploadimage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3YuUD4rPfwHQnH1fuBmGXqmoe9hT80t4',
    appId: '1:824869796384:ios:0888dd9dc27bfc9dfa5a45',
    messagingSenderId: '824869796384',
    projectId: 'upload-image-9f053',
    storageBucket: 'upload-image-9f053.appspot.com',
    iosBundleId: 'com.example.uploadimage.RunnerTests',
  );
}
