// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASPC4gQRuUqaWvDEGO-yQe02vPrcK7IkA',
    appId: '1:186822942362:web:2e44c71cdcac64699a4923',
    messagingSenderId: '186822942362',
    projectId: 'fir-basics-641b8',
    authDomain: 'fir-basics-641b8.firebaseapp.com',
    storageBucket: 'fir-basics-641b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4dj01IIOcLF2bKz5Qhv0W4ZgKHQdLRhc',
    appId: '1:186822942362:android:52fbde7c4342d9f89a4923',
    messagingSenderId: '186822942362',
    projectId: 'fir-basics-641b8',
    storageBucket: 'fir-basics-641b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpi-5Go4njieoNJyiawxYZrDkvmnMeJoA',
    appId: '1:186822942362:ios:8814f7903871bd529a4923',
    messagingSenderId: '186822942362',
    projectId: 'fir-basics-641b8',
    storageBucket: 'fir-basics-641b8.appspot.com',
    iosBundleId: 'com.example.firebaseBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpi-5Go4njieoNJyiawxYZrDkvmnMeJoA',
    appId: '1:186822942362:ios:938bb3805ad269149a4923',
    messagingSenderId: '186822942362',
    projectId: 'fir-basics-641b8',
    storageBucket: 'fir-basics-641b8.appspot.com',
    iosBundleId: 'com.example.firebaseBasics.RunnerTests',
  );
}
